apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalServices.mrpanelUiWeb.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalServices.mrpanelUiWeb.externalName }}
  ports:
    - port: {{ .Values.externalServices.mrpanelUiWeb.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: {{ .Values.cloudflare.issuerName }}
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
  name: mrpanel-ui-web-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.externalServices.mrpanelUiWeb.externalName }}
                port:
                  number: {{ .Values.externalServices.mrpanelUiWeb.port }}
  tls:
    - hosts:
        - "{{ .Values.domain }}"
        - "*.{{ .Values.domain }}"
      secretName: {{ .Values.certManager.generatedSecretName }}
